import nodemailer from 'nodemailer';
import type { AppConfig, ScrapedProduct } from './types.js';

const RETRY_DELAY_MS = 5_000;

/** Groups products by brand name for email rendering. */
function groupByBrand(products: ScrapedProduct[]): Map<string, ScrapedProduct[]> {
  const groups = new Map<string, ScrapedProduct[]>();
  for (const product of products) {
    const existing = groups.get(product.brand) ?? [];
    existing.push(product);
    groups.set(product.brand, existing);
  }
  return groups;
}

/** Escapes HTML special characters to prevent XSS in generated email. */
function escapeHtml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

/** Renders a single brand table for the email body. */
function renderBrandTable(brand: string, products: ScrapedProduct[]): string {
  const rows = products
    .map(p => {
      const thcDisplay = p.thcValue != null ? `${p.thcValue}%` : '—';
      const priceDisplay = p.priceAmount != null
        ? `$${(p.priceAmount / Math.pow(10, p.pricePrecision)).toFixed(p.pricePrecision)}`
        : '—';
      return `
      <tr>
        <td style="padding:8px 12px;border-bottom:1px solid #eee;">${escapeHtml(p.strainName)}</td>
        <td style="padding:8px 12px;border-bottom:1px solid #eee;">${escapeHtml(p.strainType ?? '—')}</td>
        <td style="padding:8px 12px;border-bottom:1px solid #eee;">${escapeHtml(thcDisplay)}</td>
        <td style="padding:8px 12px;border-bottom:1px solid #eee;">${escapeHtml(p.maxWeight ?? '—')}</td>
        <td style="padding:8px 12px;border-bottom:1px solid #eee;">${escapeHtml(priceDisplay)}</td>
      </tr>`;
    })
    .join('');

  return `
    <h2 style="color:#333;font-family:sans-serif;margin-top:24px;">${escapeHtml(brand)}</h2>
    <table style="border-collapse:collapse;width:100%;font-family:sans-serif;font-size:14px;">
      <thead>
        <tr style="background:#f5f5f5;">
          <th style="padding:8px 12px;text-align:left;border-bottom:2px solid #ddd;">Strain</th>
          <th style="padding:8px 12px;text-align:left;border-bottom:2px solid #ddd;">Type</th>
          <th style="padding:8px 12px;text-align:left;border-bottom:2px solid #ddd;">THC%</th>
          <th style="padding:8px 12px;text-align:left;border-bottom:2px solid #ddd;">Weight</th>
          <th style="padding:8px 12px;text-align:left;border-bottom:2px solid #ddd;">Price</th>
        </tr>
      </thead>
      <tbody>${rows}</tbody>
    </table>`;
}

/**
 * Builds the HTML email body from filtered products.
 * Returns a no-results paragraph when the array is empty.
 */
export function buildHtml(filteredProducts: ScrapedProduct[], date: string): string {
  if (filteredProducts.length === 0) {
    return `<p style="font-family:sans-serif;font-size:14px;color:#555;">No Viola or 710 Labs flower strains are currently listed on the Krystal Leaves menu as of ${escapeHtml(date)}.</p>`;
  }

  const groups = groupByBrand(filteredProducts);
  const tables = Array.from(groups.entries())
    .map(([brand, products]) => renderBrandTable(brand, products))
    .join('');

  return `
<!DOCTYPE html>
<html>
<head><meta charset="utf-8"></head>
<body style="margin:0;padding:16px;background:#fff;">
  <h1 style="font-family:sans-serif;font-size:20px;color:#222;">Krystal Leaves Flower Menu — ${escapeHtml(date)}</h1>
  ${tables}
  <p style="font-family:sans-serif;font-size:12px;color:#999;margin-top:32px;">Generated by dispensary-scraper</p>
</body>
</html>`;
}

/** Creates a configured Nodemailer transporter for Gmail SMTP. */
function createTransporter(config: AppConfig) {
  return nodemailer.createTransport({
    host: 'smtp.gmail.com',
    port: 587,
    secure: false, // STARTTLS
    auth: {
      user: config.gmailUser,
      pass: config.gmailPass,
    },
  });
}

/** Verifies SMTP credentials are valid. Call before running the full pipeline. */
export async function verify(config: AppConfig): Promise<void> {
  const transporter = createTransporter(config);
  await transporter.verify();
}

/** Sends the HTML email with one automatic retry on failure. */
export async function send(html: string, date: string, config: AppConfig): Promise<void> {
  const transporter = createTransporter(config);
  const mailOptions = {
    from: config.gmailUser,
    to: config.recipientEmail,
    subject: `Krystal Leaves Flower Menu — Viola & 710 Labs — ${date}`,
    html,
  };

  try {
    await transporter.sendMail(mailOptions);
  } catch (firstErr) {
    const msg = firstErr instanceof Error ? firstErr.message : String(firstErr);
    // Wait then retry once
    await new Promise<void>(r => setTimeout(r, RETRY_DELAY_MS));
    try {
      await transporter.sendMail(mailOptions);
    } catch (secondErr) {
      const msg2 = secondErr instanceof Error ? secondErr.message : String(secondErr);
      const troubleshoot = [
        'SMTP send failed after 1 retry.',
        `Error: ${msg2}`,
        'Troubleshooting:',
        '  - Verify GMAIL_USER and GMAIL_PASS in .env',
        '  - GMAIL_PASS must be a 16-character App Password (not your account password)',
        '  - Enable 2-Step Verification and generate an App Password at:',
        '    https://myaccount.google.com/apppasswords',
        '  - Ensure "Less Secure Apps" is NOT used — App Passwords are required',
        `  - First attempt error: ${msg}`,
      ].join('\n');
      const err = new Error(troubleshoot);
      (err as NodeJS.ErrnoException).code = 'EXIT_3';
      throw err;
    }
  }
}
